services:
  - type: web
    name: LingoLinq-AAC
    runtime: ruby
    plan: starter
    branch: functional-baseline
    previews:
      generation: automatic
      expireAfterDays: 7
    previewPlan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lingolinq-prod-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lingolinq-redis
          property: connectionString
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: DEFAULT_HOST
        value: lingolinq-aac.onrender.com
      - key: DEFAULT_EMAIL_FROM
        value: noreply@lingolinq-aac.onrender.com
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: SECURE_ENCRYPTION_KEY
        generateValue: true
      - key: SECURE_NONCE_KEY
        generateValue: true
      - key: COOKIE_KEY
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
  - type: worker
    name: LingoLinq-AAC-Worker
    runtime: ruby
    plan: starter
    branch: main
    previews:
      generation: automatic
      expireAfterDays: 7
    previewPlan: free
    buildCommand: "bundle install --deployment"
    startCommand: env QUEUES=priority,default,slow INTERVAL=0.1 TERM_CHILD=1 bundle exec rake environment resque:work
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lingolinq-prod-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lingolinq-redis
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: "true"

databases:
  - name: lingolinq-prod-db
    plan: basic_256mb
    databaseName: lingolinq_prod_db_xkb1
    user: lingolinq_prod_db_xkb1_user

  - name: lingolinq-redis
    plan: free
