/*
 * Ember test modules that run in the parallel `ember-shard-pool` CI job (.github/workflows/ci.yml).
 * One QUnit module name per entry, exactly as it prints before ": " in a test name.
 *
 * OPT-IN: a module is listed only after it has passed in the pool job WITHOUT the rest of the
 * suite running before it. Every module NOT listed (including every new module) runs in
 * `ember-shard-main`, in the original order, so a test that depends on an earlier test stays
 * safe there. If a listed module fails only in the pool, remove it from this list rather than
 * retrying. A renamed module silently drops out of the pool into main, which is the safe side.
 *
 * Seeded 2026-10-06 from PR #1110's first shadow run: the 287 modules whose tests all passed in
 * shard A (`/^[bhinpu]/i`) without the other modules before them. Not listed (order-dependent
 * there): Button, pictureGrabber, persistence, Unit | Route | terms-agree gate (index + bento),
 * Unit | Service | app-state effective view, Unit | Service | app-state modelling ends with
 * speak mode. Selection: tests/helpers/parallel-pool-filter.js.
 */
export default [
  "Unit | Controller | board/index word prediction locale",
  "Unit | Controller | copying-board",
  "Unit | Controller | user/board-detail display-prefs dirty check",
  "Unit | Controller | user/board-detail cancel_edit on a clean session",
  "Unit | Controller | user/board-detail display-prefs snapshot",
  "Unit | Component | copy-board hierarchy picker",
  "Unit | Controller | user/board-detail image cache",
  "Unit | Utility | board-detail-cache",
  "Unit | Utility | board-prefetch-planner",
  "Unit | loading overlay and board cache",
  "Unit | Utility | persistence json payload cache",
  "Unit | Utility | raw-events",
  "Unit | Model | board#reload_if_lite (issue #293)",
  "Unit | Model | buttonset cache fallback",
  "Unit | Component | share-board (issue #293 reload guard)",
  "Unit | Utility | special_vocalization",
  "Unit | Component | bound-select search typing",
  "Unit | Component | button-set action vocalizations",
  "Unit | Component | board-icon (compactRow vs pickOpensPreview)",
  "Unit | Component | board card density defaults",
  "Unit | Component | boards-layout-toggle",
  "Unit | Component | view-switcher availability",
  "Unit | Component | classic-view extras scroll",
  "Unit | Utility | tours registry \u2014 classic branch",
  "Unit | Component | classic-view observer kick",
  "Unit | Controller | application \"Try New Style\"",
  "Unit | Helper | break-on-separators",
  "Unit | Helper | letter-stagger",
  "Unit | Utility | dashboard sections layout engine",
  "Unit | Utility | dashboard sections layoutPresentation",
  "Unit | Utility | session_user_wait",
  "Unit | Route | setup (retired guard)",
  "Unit | Route | board cold-boot view choice",
  "new-board Generate with AI, Not now",
  "BoardPreviewCanvasComponent",
  "Integration | Component | confirm board dialogs",
  "BoardDetailsController",
  "BoardController",
  "BoardIndexController",
  "BoardStatsController",
  "ButtonSettingsController",
  "ButtonStashController",
  "HighlightController",
  "ImportingBoardsController",
  "IndexController",
  "InlineVideoController",
  "PremiumRequiredController",
  "UserController",
  "UserBoardDetailController \u2014 Customize Menu flag gate",
  "UserEditController",
  "UserIndexController",
  "UserLogController",
  "UserLogController location map",
  "UserLogsController",
  "UserPasswordResetController",
  "UserPreferencesController",
  "UserStatsController",
  "UtteranceController",
  "Integration | Component | app-navbar signed-out Sign In",
  "Integration | available-boards-section folders accordion",
  "Integration | big-button nested open",
  "Integration | Component | board-categorize-coming-soon",
  "Integration | board-detail-grid empty state",
  "Integration | board-detail-grid prediction slot label",
  "Integration | Component | bound-select paging",
  "Integration | Component | bound-select search template",
  "Integration | Component | dashboard/classic-account-rail supervisors row",
  "Integration | Component | dashboard/classic-rail admin slot",
  "Integration | Component | dashboard/classic-rail-basic-access",
  "Integration | Component | dashboard/classic-rail org admin rows",
  "Integration | Component | dashboard/classic-rail rooms only",
  "Integration | modal-container confirm-view-style-change",
  "Integration | {{display-name}} helper",
  "Integration | \"No name\" sentinel across real surfaces",
  "Integration | display-style triggerless",
  "Integration | Component | focused-page-label",
  "Integration | gif search runs",
  "Integration | Helper | basic-try-home",
  "Integration | inbox footer scannable",
  "Integration | Component | list-filter",
  "Unit | modal close handlers are bound before render",
  "Unit | modal scroll lock",
  "Integration | modal @opening callback",
  "Integration | Modifier | fit-or-select",
  "Integration | mut as an invoked @action",
  "Integration | Component | pause-logging-button",
  "Integration | prediction text position",
  "Integration | raw_events press backstop",
  "Integration | Component | sidebar-tease toggle",
  "Integration | speak bar | board-intro anchor",
  "Unit | Controller | system-settings/email-edit handlers",
  "Integration | Template | system-settings input fields",
  "Integration | terms-agree scannable markup",
  "Integration | view-switcher menu order",
  "Badge",
  "Board",
  "Boardversion",
  "Buttonset",
  "Image",
  "Unit",
  "User",
  "Utterance",
  "Unit | Utility | board_grid",
  "Unit | Component | account-rail activeRow",
  "Unit | Component | account-rail collapse",
  "Unit | Component | basic-try-home-button finish",
  "Unit | Component | basic-try-home-button",
  "Unit | Component | beta feedback form",
  "Unit | Component | board-actions relocated rows",
  "Unit | Component | board categorization default",
  "Unit | Component | board-detail-grid category order",
  "Unit | board-picker category order",
  "Unit | board-picker category load race",
  "Unit | board-picker category tagged sub-boards",
  "Unit | board-preview pick mode",
  "Unit | Component | bound-select auto-flip",
  "Unit | Component | button-settings action switch",
  "Unit | Component | classic-account-rail activeRow",
  "Unit | Component | classic-view caseload landing gaps",
  "Unit | Component | classic-view communicators tab",
  "Unit | Component | classic-view Extras landing",
  "Unit | Component | classic-view run evaluation",
  "Unit | Component | classic-view supervisee landing",
  "Unit | Component | confirm-notify-user share send",
  "Unit | Component | confirm remove board action lock",
  "Unit | Component | copy-board close handler",
  "Unit | copy-board dismissal",
  "Unit | Component | copy-progress-drawer edit route",
  "Unit | Component | copying-board completion notice",
  "Unit | Component | create-board-new image drop",
  "Unit | Component | create-board-new steppers",
  "Unit | Component | dashboard compressed home",
  "Unit | Component | edit-board-details discard leaves the rename behind",
  "Unit | Component | eu-ai-parental-consent",
  "Unit | Component | eval-quick-screen cancel",
  "Unit | Component | gif opening callback",
  "Unit | Component | password-field",
  "Unit | Component | share-utterance contact id",
  "Unit | Component | speak-menu held thoughts",
  "Unit | Component | speak-menu parked ordering",
  "Unit | Component | supervision-settings standalone",
  "Unit | tour-board-picker init",
  "Unit | Component | view-switcher back trap",
  "Unit | Component | view-switcher boards owner",
  "Unit | Component | view-switcher compressed view",
  "Unit | Component | view-switcher logs landing",
  "Unit | Component | view-switcher modern landing",
  "Unit | Component | view-switcher obf boards",
  "Unit | Controller | board edit route while modeling",
  "Unit | Controller | board/index prediction board scope",
  "Unit | Controller | board/index sidebar width reservation",
  "Unit | Controller | board/index suggestions write after destroy",
  "Unit | Controller | board-picker pick for a communicator",
  "Unit | Controller | caseload deep link vs Needs attention",
  "Unit | Controller | organization focusedRoomsLabel",
  "Unit | Controller | organization showOrgSwitcher",
  "Unit | Controller | organization rooms filter",
  "Unit | Controller | organization roomsPageActive",
  "Unit | Controller | organization roomsSectionActive",
  "Unit | Controller | organization tab dropdown label",
  "Unit | Controller | organizations list load",
  "Unit | Controller | prediction lookup scope",
  "Unit | Controller | prediction symbol scope",
  "Unit | Controller | system-settings/features save errors",
  "Unit | Controller | user/board-detail category order",
  "Unit | Controller | user/board-detail category grouping is per-user",
  "Unit | Controller | user/board-detail discard from a collapsed prefs panel",
  "Unit | Controller | user/board-detail discard rebuilds instead of blanking",
  "Unit | Controller | user/board-detail display-pref steppers",
  "Unit | Controller | user/board-detail rebuild must not fold a rename",
  "Unit | Controller | user/board-detail grid geometry",
  "Unit | Controller | user/board-detail larger-screen overlay",
  "Unit | Controller | user/board-detail modelling symbol scope",
  "Unit | Controller | user/board-detail pause logging row",
  "Unit | Controller | user/board-detail prediction hold",
  "Unit | Controller | user/board-detail chip image apply",
  "Unit | Controller | user/board-detail save image persist",
  "Unit | Controller | user/board-detail try-back",
  "Unit | Controller | user/board-detail URL-link select_button",
  "Unit | Controller | user/board-detail view-mode actions",
  "Unit | Controller | user showClassicAccountRail",
  "Unit | Controller | user flush-top workspace",
  "Unit | Controller | user/index isSelf",
  "Unit | user/log same_author",
  "Unit | Controller | user/logs reset_params",
  "Unit | Controller | user nav context",
  "Unit | Ember 5.12 migration regression > Class 1 \u2014 native arrays have no Ember array-extension methods",
  "Unit | Ember 5.12 migration regression > Class 2 \u2014 @each reactivity over an A()-wrapped array",
  "Unit | Ember 5.12 migration regression > test-waiters \u2014 a registered waiter tracks in-flight async",
  "Unit | Helper | basic-try-home",
  "Unit | Helper | truth helpers",
  "Unit | Model | board reload_including_all_downstream",
  "Unit | Route | Basic landings on a slow load",
  "Unit | Route | Basic logs landing",
  "Unit | Route | Basic view direct landings",
  "Unit | Route | Basic view landings for Modern-only pages",
  "Unit | Route | home-boards redirect",
  "Unit | Route | index Basic supporter login",
  "Unit | Route | index login entry and Basic landings",
  "Unit | Route | index session resume",
  "Unit | Route | organization permissions wait",
  "Unit | Serializer | user supervisees offline",
  "Unit | Service | app-state clear_user_state handoffs",
  "Unit | Service | app-state density scope",
  "Unit | Service | app-state link_disabled",
  "Unit | Service | copy-progress percent",
  "Unit | stashes reconnect drain",
  "Unit | Service | telemetry",
  "Unit | Model | user organization access",
  "Unit | Utility | action lock",
  "Unit | Utility | admin_nav",
  "Unit | Utility | api error message",
  "Unit | Utility | ai_word_predictor article50 degrade",
  "Unit | Utility | ai_word_predictor article50 degrade > speak mode",
  "Unit | Utility | article50 gate > needsAcknowledgement",
  "Unit | Utility | article50 gate > presentBlockingGate",
  "Unit | Utility | article50 gate > maybeShowSessionEntryGate",
  "Unit | Utility | article50 gate > onlyIfGenuinelyResolved",
  "Unit | Utility | article50 gate > art50DisclosureUrl",
  "Unit | Utility | article50 gate > art50Subject",
  "Unit | Utility | article50 gate > needsAcknowledgement in speak mode (supporter modeling for a communicator)",
  "Unit | Utility | article50 gate > art50UserId",
  "Unit | Utility | article50 gate > session-entry gate survives the subject change",
  "Unit | Utility | article50-session-entry (routes/index.js & routes/bento.js wiring)",
  "Unit | Utility | badge_display",
  "Unit | Utility | basic_landing Extras",
  "Unit | Utility | basic_landing modern landing",
  "Unit | Utility | basic_landing Basic Access",
  "Unit | Utility | basic_landing redirect history",
  "Unit | Utility | basic_landing supervisee",
  "Unit | Utility | basic_landing",
  "Unit | Utility | board attribution",
  "Unit | Utility | board_categories",
  "Unit | Utility | board_display_locale",
  "Unit | Utility | board_grid trim keeps overflow",
  "Unit | Utility | board-key-from-input",
  "Unit | Utility | board_picker_landing",
  "Unit | Utility | boards-page-list-cache",
  "Unit | Utility | compressed_view_state",
  "Unit | Utility | dashboard sections",
  "Unit | Utility | eval_auto_score",
  "Unit | Utility | eval_grid_sweep",
  "Unit | Utility | eval_prompt_hierarchy",
  "Unit | Utility | eval_recommend.fromComprehensive",
  "Unit | Utility | eval_recommend.fromTargeted",
  "Unit | Utility | eval_recommend",
  "Unit | Utility | eval_session",
  "Unit | eval_workbook LCD coverage",
  "Unit | eval_workbook derivePrefill",
  "Unit | Utility | eval_workbook mergeForSend",
  "Unit | Utility | folders_panel_state",
  "Unit | Utility | home board assignment",
  "Unit | Utility | home tour navPillSummary",
  "Unit | Utility | modal paging",
  "Unit | Utility | parts_of_speech resolver",
  "Unit | Utility | prediction lookup ids are scoped to the speaking user",
  "Unit | Utility | prediction memo is scoped to the speaking user",
  "Unit | Utility | prediction symbol from any loaded board",
  "Unit | Utility | prediction symbols from a freshly fetched board",
  "Unit | Utility | prediction symbol pairing",
  "Unit | Controller | prediction suppressed on yes/no",
  "Unit | Controller | prediction placement",
  "Unit | Utility | prediction symbols are scoped to the speaking user",
  "Unit | Utility | primary_nav",
  "Unit | Utility | proportions",
  "Unit | Utility | remote_modeling",
  "Unit | Utility | report summary",
  "Unit | Utility | rooms_nav",
  "Unit | Utility | session_history",
  "Unit | Utility | standalone idb shim",
  "Unit | Utility | stub restoration protection",
  "Unit | Utility | tours classic-home Actions tab",
  "Unit | Utility | tours/registry",
  "Unit | Utility | user_filter",
  "Unit | Utility | confirm_view_style_change",
  "Unit | view style coverage",
  "Unit | view style coverage > the body class tracks the resolved style",
  "Unit | view style with a plain-object user",
  "board-roots",
  "boardGrabber",
  "boardHierarchy",
  "boundClasses",
  "i18n",
  "persistence-sync",
  "progress_tracker",
  "Unit | Route | user/board-detail scanning re-arm after grid build",
  "utterance",
];
