# Public/system vocabulary boards owned by the lingolinq content account.
module SystemBoardSources
  USER_NAME = ENV.fetch('SYSTEM_BOARD_USER_NAME', 'lingolinq').freeze
  CRISIS_VOCABULARY_SLUG = 'crisis-vocabulary'.freeze
  CRISIS_VOCABULARY_OBZ = Rails.root.join('public/system-boards/crisis-vocabulary.obz').freeze
  SENNER_BAUD_SLUG = 'senner-baud'.freeze
  # The Senner-Baud set is ~12 MB, so it is hosted in the static S3 bucket
  # (alongside avatars / AI assets) rather than committed to the repo. The seed
  # fetches it from the running environment's STATIC_S3_BUCKET, falling back to
  # the public prod bucket for local/dev (whose own static bucket is private).
  SENNER_BAUD_OBZ_KEY = 'system-boards/senner-baud.obz'.freeze
  SENNER_BAUD_OBZ_FALLBACK_BUCKET = 'lingolinq-prod-static'.freeze
  # Local/dev fallback when STATIC_S3 is unreachable. Prefer SENNER_BAUD_OBZ_PATH,
  # else the curated export under tmp/seed-boards/ (gitignored — never commit OBZs).
  SENNER_BAUD_LOCAL_OBZ = Rails.root.join('tmp/seed-boards/SennerBaudSocialPages60ll.obz').freeze
  SENNER_BAUD_NAME = 'Senner-Baud Social Pages'.freeze
  SIGNUP_LIBRARY_SLUGS = %w[quick-core-60 vocal-flair-60 vocal-flair-84 crisis-vocabulary senner-baud].freeze
  # Intentionally empty: an in-request sync copy of vocal-flair-84 exceeds Rack::Timeout
  # (~16s) on staging and 500s signup after the user row is already persisted
  # (see docs/task-management/2026-07-28-staging-registration-timeout.md).
  # Keep the constant so a future small/root-only sync board can opt back in.
  SIGNUP_SYNC_SLUGS = [].freeze
  # Utility boards copied async so default sidebar entries can resolve to user-owned copies.
  SIDEBAR_COPY_SLUGS = %w[yesno inflections].freeze
  # Prefer VF84 first among async jobs so home-board pickers see it soon after signup.
  SIGNUP_ASYNC_SLUGS = (
    %w[vocal-flair-84] +
    SIDEBAR_COPY_SLUGS +
    (SIGNUP_LIBRARY_SLUGS - %w[vocal-flair-84] - SIGNUP_SYNC_SLUGS)
  ).freeze
  SPANISH_LIBRARY_SLUGS = %w[quick-core-60-es vocal-flair-60-es].freeze
  SPANISH_SOURCE_MAP = {
    'quick-core-60-es' => 'quick-core-60',
    'vocal-flair-60-es' => 'vocal-flair-60'
  }.freeze
  # Generated by SystemSidebarBoards (not translated from English inflections).
  SPANISH_SIDEBAR_COPY_SLUGS = %w[inflections-es].freeze

  def self.board_key(slug)
    "#{USER_NAME}/#{slug}"
  end

  def self.owner
    User.find_by(user_name: USER_NAME)
  end

  # Idempotent: ensures the configured system board user has crisis-vocabulary from the committed OBZ.
  def self.ensure_crisis_vocabulary!(owner = nil)
    owner ||= self.owner
    return nil unless owner

    key = board_key(CRISIS_VOCABULARY_SLUG)
    existing = Board.find_by_path(key)
    if existing
      existing.public = true
      existing.settings['name'] ||= "Crisis Vocabulary"
      existing.settings['unlisted'] = false
      existing.generate_stats
      existing.save_without_post_processing
      return existing
    end

    unless File.exist?(CRISIS_VOCABULARY_OBZ)
      Rails.logger.warn("[SystemBoardSources] Missing #{CRISIS_VOCABULARY_OBZ} — cannot import crisis vocabulary board")
      return nil
    end

    require Rails.root.join('lib', 'converters', 'lingo_linq')
    boards = Converters::LingoLinq.from_obz(CRISIS_VOCABULARY_OBZ.to_s, 'user' => owner, 'boards' => {})
    return nil if boards.blank?

    root = boards.first
    boards.each_with_index do |board, idx|
      if idx.zero?
        board.public = true
        board.key = key if board.user_id == owner.id
        board.settings['name'] ||= "Crisis Vocabulary"
        board.settings['unlisted'] = false
      else
        board.public = true
        board.settings['unlisted'] = true
      end
      board.generate_stats
      board.save_without_post_processing
    end

    root.instance_variable_set(:@buttons_changed, 'import')
    root.instance_variable_set(:@brand_new, true)
    root.save!

    Board.find_by_path(key) || root
  end

  # Candidate public S3 URLs for the Senner-Baud OBZ: the running environment's
  # static bucket first, then the public prod bucket as a fallback (so local/dev,
  # whose own static bucket is private/KMS-encrypted, still resolves it).
  def self.senner_baud_obz_urls
    buckets = [ENV['STATIC_S3_BUCKET'].presence, SENNER_BAUD_OBZ_FALLBACK_BUCKET].compact.uniq
    # Drop anything that isn't a syntactically valid S3 bucket name, so a
    # malformed STATIC_S3_BUCKET can't produce a bogus URL (it would just 404
    # and waste a request); fetch_senner_baud_obz then logs + returns nil.
    buckets = buckets.select { |b| b =~ /\A[a-z0-9][a-z0-9.\-]{1,61}[a-z0-9]\z/ }
    buckets.map { |b| "https://#{b}.s3.amazonaws.com/#{SENNER_BAUD_OBZ_KEY}" }
  end

  # Downloads the Senner-Baud OBZ from S3, returning [url, body] or nil.
  def self.fetch_senner_baud_obz
    require 'safe_http'
    senner_baud_obz_urls.each do |url|
      begin
        resp = SafeHttp.get(url, timeout: 300, connecttimeout: 30)
        return [url, resp.body] if resp && resp.success?
        Rails.logger.warn("[SystemBoardSources] Senner-Baud OBZ #{url} -> HTTP #{resp && resp.code}")
      rescue => e
        Rails.logger.warn("[SystemBoardSources] Senner-Baud OBZ fetch failed for #{url}: #{e.message}")
      end
    end
    nil
  end

  # Local path for Senner-Baud when S3 is unavailable (WSL/dev). ENV override first.
  def self.local_senner_baud_obz_path
    env_path = ENV['SENNER_BAUD_OBZ_PATH'].to_s.strip.presence
    return env_path if env_path && File.exist?(env_path)
    return SENNER_BAUD_LOCAL_OBZ.to_s if File.exist?(SENNER_BAUD_LOCAL_OBZ)
    nil
  end

  # After from_obz, button load_board.key can lag the resolved board key (suffix
  # collisions leave id pointing at keyboard while key still says keyboard_7).
  # Rewrite key to match the board found by id whenever they disagree.
  def self.sync_load_board_keys!(boards)
    Array(boards).each do |board|
      buttons = board.settings && board.settings['buttons']
      next if buttons.blank?

      changed = false
      buttons.each do |btn|
        lb = btn['load_board']
        next unless lb.is_a?(Hash) && lb['id'].present?

        target = Board.find_by_global_id(lb['id']) rescue nil
        next unless target
        next if lb['key'] == target.key

        lb['key'] = target.key
        changed = true
      end
      next unless changed

      board.settings['buttons'] = buttons
      board.generate_stats
      board.save_without_post_processing
    end
  end

  # Signup / library slug for an OpenAAC quick-core-N.obz filename, or nil.
  def self.quick_core_root_slug_for_filename(filename)
    m = filename.to_s.match(/\Aquick-core-(\d+)\.obz\z/i)
    m ? "quick-core-#{m[1]}" : nil
  end

  # Assign board.key when the target path is free (or already this board).
  # Returns true if the board now has new_key.
  def self.rekey_board!(board, new_key)
    return true if board.key == new_key

    occupied = Board.find_by_path(new_key)
    if occupied && occupied.id != board.id
      Rails.logger.warn("[SystemBoardSources] Cannot re-key #{board.key} -> #{new_key}; target occupied by board #{occupied.global_id}")
      return false
    end

    board.key = new_key
    board.generate_stats
    board.save_without_post_processing
    true
  end

  # Senner OBZ boards often use bare keys like lingolinq/core-60 (no "-child" suffix).
  # That is the same slot OpenAAC Quick Core uses for its product root before we
  # re-key to quick-core-60. Move bare core-N roots onto senner-baud-core-N so
  # db:seed can place Quick Core at lingolinq/quick-core-N without colliding.
  # Child keys (core-60-when, etc.) are left alone so shared Core pages can be reused.
  def self.relinquish_bare_core_roots!(boards, owner)
    Array(boards).each do |board|
      next unless board && board.user_id == owner.id
      m = board.key.to_s.match(%r{\A[^/]+/(core-\d+)\z})
      next unless m

      new_key = board_key("senner-baud-#{m[1]}")
      next if board.key == new_key

      if rekey_board!(board, new_key)
        Rails.logger.info("[SystemBoardSources] Relinquished bare core root #{m[1]} -> #{new_key}")
      end
    end
  end

  # OpenAAC quick-core-N.obz roots import as core-N; signup expects quick-core-N.
  def self.rekey_quick_core_root!(root, filename, owner)
    slug = quick_core_root_slug_for_filename(filename)
    return nil unless slug && root && root.user_id == owner.id

    new_key = board_key(slug)
    return root.key if root.key == new_key

    if rekey_board!(root, new_key)
      new_key
    else
      nil
    end
  end

  # Idempotent: ensures the system board user has the Senner-Baud social pages set
  # from the OBZ hosted in the static S3 bucket. Mirrors ensure_crisis_vocabulary!,
  # but sources the (large) OBZ from S3 rather than the repo. Falls back to a local
  # tmp/seed-boards export when S3 is unreachable. The export's root is the
  # "greetings" page; we re-key it to <user>/senner-baud and give it the set's
  # name so it reads cleanly in the signup library.
  def self.ensure_senner_baud!(owner = nil)
    owner ||= self.owner
    return nil unless owner

    key = board_key(SENNER_BAUD_SLUG)
    existing = Board.find_by_path(key)
    if existing
      existing.public = true
      existing.settings['name'] ||= SENNER_BAUD_NAME
      existing.settings['unlisted'] = false
      existing.generate_stats
      existing.save_without_post_processing
      return existing
    end

    require Rails.root.join('lib', 'converters', 'lingo_linq')
    require 'tempfile'
    boards = nil

    fetched = fetch_senner_baud_obz
    if fetched
      Tempfile.create(['senner_baud_', '.obz']) do |tmp|
        tmp.binmode
        tmp.write(fetched.last)
        tmp.close
        boards = Converters::LingoLinq.from_obz(tmp.path, 'user' => owner, 'boards' => {})
      end
    else
      local_path = local_senner_baud_obz_path
      if local_path
        Rails.logger.info("[SystemBoardSources] Senner-Baud OBZ using local fallback #{local_path}")
        boards = Converters::LingoLinq.from_obz(local_path, 'user' => owner, 'boards' => {})
      else
        Rails.logger.warn("[SystemBoardSources] Could not fetch Senner-Baud OBZ from S3 (#{senner_baud_obz_urls.join(', ')}) and no local file — skipping import")
        return nil
      end
    end
    return nil if boards.blank?

    root = boards.first
    boards.each_with_index do |board, idx|
      if idx.zero?
        board.public = true
        board.key = key if board.user_id == owner.id
        board.settings['name'] = SENNER_BAUD_NAME
        board.settings['unlisted'] = false
      else
        board.public = true
        board.settings['unlisted'] = true
      end
      board.generate_stats
      board.save_without_post_processing
    end

    # Free bare core-N keys before OpenAAC Quick Core import (seed order: Senner then OpenAAC).
    relinquish_bare_core_roots!(boards, owner)
    sync_load_board_keys!(boards)

    root.instance_variable_set(:@buttons_changed, 'import')
    root.instance_variable_set(:@brand_new, true)
    root.save!

    Board.find_by_path(key) || root
  rescue ActiveRecord::RecordNotUnique => e
    # A board already occupies <user>/senner-baud (a concurrent seed, or a
    # partial prior run that imported then died before this re-key). Don't abort
    # the whole seed; finalize and surface the existing board so callers stay
    # idempotent and never receive a half-published board.
    Rails.logger.warn("[SystemBoardSources] Senner-Baud re-key collided on #{key} (#{e.message}); returning existing board")
    existing = Board.find_by_path(key)
    if existing
      existing.public = true
      existing.settings['name'] ||= SENNER_BAUD_NAME
      existing.settings['unlisted'] = false
      existing.generate_stats
      existing.save_without_post_processing
    end
    existing
  end
end
